### ISSUE TITLE
findTargetElement does not accept SVGElement

### ISSUE THREAD

**Issue by adriancooney** [simplabs/qunit-dom#75]
If I pass an SVGElement into `assert.dom(<svg element>)` and try to run any assertions, it fails because it requires a [`HTMLElement` explicitly](https://github.com/simplabs/qunit-dom/blob/8ea2de84d9f0ce1aa5b639024d66cf808176650e/lib/assertions.js#L657-L678). Maybe move up the inheritance chain in the `instanceof` check to `Element` rather than `HTMLElement` in the check?

```
let svgElement = document.querySelectorElement("svg"); // Element retrieved manually because too complicated for selector
assert.dom(svgElement).hasAttribute("width", "100");
```

Throws:
```
TypeError: Unexpected Parameter: [object SVGGElement]
--
  | at DOMAssertions.findTargetElement (http://localhost:7357/assets/test-support.js:22780:15)
  | at DOMAssertions.hasAttribute (http://localhost:7357/assets/test-support.js:22285:26)
  | at Object._callee21$ (http://localhost:7357/assets/tests.js:140150:76)
  | at tryCatch (http://localhost:7357/assets/vendor.js:10983:40)
  | at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:11274:22)
  | at Generator.prototype.(anonymous function) [as next] (http://localhost:7357/assets/vendor.js:11035:21)
  | at step (http://localhost:7357/assets/tests.js:139513:32)
  | at http://localhost:7357/assets/tests.js:139524:15
  | at <anonymous>
```

**Comment by Turbo87** [comment]
> Maybe move up the inheritance chain in the instanceof check to Element rather than HTMLElement?

yeah that sounds like a good solution. can you open a pull request?

**Comment by adriancooney** [comment]
Thanks for the reply @Turbo87. Sure! Just threw one together here: https://github.com/simplabs/qunit-dom/pull/76
